function StormEventsdetailsd2022 = importfileF(filename, dataLines)
%IMPORTFILE2 Import data from a text file
%  STORMEVENTSDETAILSD2022 = IMPORTFILE2(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  STORMEVENTSDETAILSD2022 = IMPORTFILE2(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  StormEventsdetailsd2022 = importfile2("C:\Users\Andrea\Desktop\Drive Andrea\Data Analysis\Wheather events\Main\StormEvents_details_d2022.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-May-2023 22:04:09

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 51);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "STATE", "Var10", "Var11", "MONTH_NAME", "EVENT_TYPE", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "END_DATE_TIME", "Var21", "Var22", "Var23", "Var24", "DAMAGE_PROPERTY", "DAMAGE_CROPS", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44", "BEGIN_LAT", "BEGIN_LON", "Var47", "Var48", "Var49", "Var50", "Var51"];
opts.SelectedVariableNames = ["STATE", "MONTH_NAME", "EVENT_TYPE", "END_DATE_TIME", "DAMAGE_PROPERTY", "DAMAGE_CROPS", "BEGIN_LAT", "BEGIN_LON"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "categorical", "string", "string", "categorical", "categorical", "string", "string", "string", "string", "string", "string", "datetime", "string", "string", "string", "string", "double", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "double", "double", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var10", "Var11", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var21", "Var22", "Var23", "Var24", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44", "Var47", "Var48", "Var49", "Var50", "Var51"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "STATE", "Var10", "Var11", "MONTH_NAME", "EVENT_TYPE", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var21", "Var22", "Var23", "Var24", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44", "Var47", "Var48", "Var49", "Var50", "Var51"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "END_DATE_TIME", "InputFormat", "dd-MMM-yy HH:mm:ss");
opts = setvaropts(opts, ["DAMAGE_PROPERTY", "DAMAGE_CROPS"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["DAMAGE_PROPERTY", "DAMAGE_CROPS"], "ThousandsSeparator", ",");

% Import the data
StormEventsdetailsd2022 = readtable(filename, opts);

end