function data2021S1 = importxlsx(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  DATA2021S1 = IMPORTFILE1(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  DATA2021S1 = IMPORTFILE1(FILE, SHEET) reads from the specified
%  worksheet.
%
%  DATA2021S1 = IMPORTFILE1(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  data2021S1 = importfile1("C:\Users\Andrea\Desktop\Drive Andrea\3. Viajes\1. Cali 15-19 de Abril\Universidad del Valle\1. Wheather events\Main\Final\data2021.xlsx", "2train5", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Apr-2024 15:06:38

%% Input handling

% If no sheet is specified, read from 2train5
if nargin == 1 || isempty(sheetName)
    sheetName = "2train5";
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 48);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "STATE", "Var10", "Var11", "MONTH_NAME", "EVENT_TYPE", "Var14", "Var15", "Var16", "Var17", "BEGIN_DATE_TIME", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44", "BEGIN_LAT", "BEGIN_LON", "END_LAT", "END_LON"];
opts.SelectedVariableNames = ["STATE", "MONTH_NAME", "EVENT_TYPE", "BEGIN_DATE_TIME", "BEGIN_LAT", "BEGIN_LON", "END_LAT", "END_LON"];
opts.VariableTypes = ["char", "char", "char", "char", "char", "char", "char", "char", "categorical", "char", "char", "categorical", "categorical", "char", "char", "char", "char", "datetime", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var10", "Var11", "Var14", "Var15", "Var16", "Var17", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "STATE", "Var10", "Var11", "MONTH_NAME", "EVENT_TYPE", "Var14", "Var15", "Var16", "Var17", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44"], "EmptyFieldRule", "auto");

% Import the data
data2021S1 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    data2021S1 = [data2021S1; tb]; %#ok<AGROW>
end

end